Adds databases for a failing unit test: JumpType fails because of a duplicate.
Now it does (with the proper UNIQUE index that I've added but not in
normal chronojump):
sqlite3.IntegrityError: UNIQUE constraint failed: jumpType.name